#!/bin/bash

RUN_AS=${1:-'default_user'}
MY_PATH=`dirname "$0"`

echo Process will run as "$RUN_AS"
echo

for i in $(cat "$MY_PATH"/serverlist)
do
  echo $i
  echo ssh -i ~/.ssh/locust.pem -t $RUN_AS@$i
  ssh -i ~/.ssh/locust.pem -t $RUN_AS@$i 'sudo mkdir -p /opt/swarm/www/utils && sudo chmod 777 -R /opt/swarm/www  && rm -f /opt/swarm/www/* && rm -f /opt/swarm/www/utils/*'
  echo "$MY_PATH"/python_scripts/
  for j in $(echo `ls "$MY_PATH"/python_scripts/`)
  do
    scp -i ~/.ssh/locust.pem  "$MY_PATH"/python_scripts/$j $RUN_AS@$i:/opt/swarm/www
  done 

  for j in $(echo `ls "$MY_PATH"/python_scripts/utils/`)
  do
    scp -i ~/.ssh/locust.pem  "$MY_PATH"/python_scripts/utils/$j $RUN_AS@$i:/opt/swarm/www/utils
  done 

  ssh -i ~/.ssh/locust.pem  -t $RUN_AS@$ 'sudo chmod 755 -R /opt/swarm/www'
  ssh -i ~/.ssh/locust.pem  -t $RUN_AS@$i 'sudo chown -R root:root /opt/swarm/www'
done
